### PR TITLE
add upload artifacts from build step

### PR DESCRIPTION
**Pull request by szlatkow**

### CODE REVIEW

**Review by aleks-ivanov — CHANGES_REQUESTED** [review]
Unify

**Review by aleks-ivanov — APPROVED** [review]

**Comment by aleks-ivanov** [comment]
@szlatkow  test my changes and if they work, Squash and merge the PR.

**Comment by szlatkow** [comment]
@aleks-ivanov I removed the "--no-build"  argument from the "Run unit tests" step tested the changes that u made and everything is working

**Comment by aleks-ivanov** [comment]
> @aleks-ivanov I removed the "--no-build" argument from the "Run unit tests" step tested the changes that u made and everything is working

Sure, BUT let's try to decrease the computing bandwidth and find a way to make it work with no-build

**Comment by szlatkow** [comment]
@aleks-ivanov I found a solution to the problem in the [dotnet test](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test) documentation. I tested it and it is working.

**Comment by aleks-ivanov** [comment]
> @aleks-ivanov I found a solution to the problem in the [dotnet test](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test) documentation. I tested it and it is working.

Great. Apply that solution to all.

**Pull request merged**
